### ISSUE TITLE
error on installation

### ISSUE THREAD

**Issue by rcdosado** [mohammadfayaj/Django-Donatroy#1]
`pip install -r requirements.txt` giving me this error:
"""
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\<USER>\AppData\Local\Temp\pip-build-1kujwf04\cryptography\setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\<USER>\AppData\Local\Temp\pip-build-1kujwf04\cryptography\

"""

i'm using windows 10, python 3.6

**Comment by mohammadfayaj** [comment]
I tested it in my machine.It just worked fine. So there is no error in code or requirements.txt file.
You can try this steps :
1. python3 -m pip install --upgrade pip --target /usr/lib64/az/lib/python3.6/site-packages/
2. pip install setuptools-rust and
3. if it don't work try to remove cryptography==3.4.7 from requirements.txt

This might be helpful for you https://github.com/Azure/azure-cli/issues/16858

**Comment by mohammadfayaj** [comment]
> 
> 
> `pip install -r requirements.txt` giving me this error:
> """
> Traceback (most recent call last):
> File "", line 1, in
> File "C:\Users<USER>\AppData\Local\Temp\pip-build-1kujwf04\cryptography\setup.py", line 14, in
> from setuptools_rust import RustExtension
> ModuleNotFoundError: No module named 'setuptools_rust'
> 
> ```
> ----------------------------------------
> ```
> 
> Command "python setup.py egg_info" failed with error code 1 in C:\Users<USER>\AppData\Local\Temp\pip-build-1kujwf04\cryptography\
> 
> """
> 
> i'm using windows 10, python 3.6
